{% set version = "20170524" %}

package:
  name: texlive-core
  version: {{ version }}

source:
  url: ftp://tug.org/texlive/historic/2017/texlive-{{ version }}-source.tar.xz
  sha256: 0161695304e941334dc0b3b5dabcf8edf46c09b7bc33eea8229b5ead7ccfb2aa

build:
  number: 2
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    #- xorg-libxrender
    #- xorg-libxext
    #- xorg-libxau
    - pkg-config
    - make
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - {{ cdt('libxau-devel') }}     # [linux]
  host:
    - cairo 1.14.*
    - gmp 6.1.*
    - icu 58.*
    - mpfr 3.1.*
    - pixman 0.34.*
    - freetype 2.8.*
    - libpng >=1.6.32,<1.6.35
    - zlib 1.2.11
    - perl 5.26.2
    - fontconfig
    - graphite2
    - harfbuzz
  run:
    - cairo 1.14.*
    - gmp 6.1.*
    - icu 58.*
    - mpfr 3.1.*
    - pixman 0.34.*
    - freetype 2.8.*
    - libpng >=1.6.32,<1.6.35
    - zlib 1.2.11
    - perl 5.26.2

test:
  commands:
    - pdftex --version
    - bibtex --version
    # Test the symlinks.
    - pdflatex --version
    - latex --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.tug.org/texlive/
  license: GPL-2.0+ and GPL-2.0 and GPL-3.0 and LPPL-1.3c and LPPL-1.0 and Artistic-1.0 and Apache-2.0 and MIT and BSD-3-Clause
  summary: 'An easy way to get up and running with the TeX document production system.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
